### ISSUE TITLE
import-meta-env/unplugin fails to initialize in Vite+Vue app

### ISSUE THREAD

**Issue by lfaletti** [runtime-env/import-meta-env#1250]
Initialization of application does not work adding unplugin (npm run dev or npm run build)

I get this exception:

```
failed to load config from..\app\vite.config.js
error when starting dev server:
TypeError [ERR_INVALID_ARG_TYPE]: The "paths[1]" argument must be of type string. Received undefined
    at validateString (node:internal/validators:162:11)
    at resolve (node:path:171:9)
at resolveEnvExampleKeys (...\app\node_modules\@import-meta-env\unplugin\dist\index.js:109:48)
    at ...\app\node_modules\@import-meta-env\unplugin\dist\index.js:1445:26
    at Object.<anonymous> (...\app\node_modules\unplugin\dist\index.js:1674:32)
    at Object.<anonymous> (...\app\vite.config.js:40:29)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at _require.extensions.<computed> [as .js] (file:///.../app/node_modules/vite/dist/node/chunks/dep-52909643.js:66350
```
vite.config.js configs tried:

1. 
```
import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'
import ImportMetaEnvPlugin from "@import-meta-env/unplugin"

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [    
    ImportMetaEnvPlugin.vite({
      env: ".env"
    }),
    vue()
  ],
  envDir: './',
  server: {
    port: 3000,
    host: "0.0.0.0"
  },
  base: "/test/"
})

```

2. Using `ImportMetaEnvPlugin.vite()` , same error.

package.json:

```
{
  "name": "x-test",
  "version": "0.0.0",
  "private": true,
  "scripts": {
    "dev": "vite",
    "build": "vite build",
    "preview": "vite preview"
  },
  "dependencies": {
    "pinia": "^2.1.7",
    "vue": "^3.3.4",
    "vue-router": "^4.2.4"
  },
  "devDependencies": {
    "@import-meta-env/cli": "^0.6.8",
    "@import-meta-env/unplugin": "^0.5.1",
    "@vitejs/plugin-vue": "^4.3.4",
    "autoprefixer": "^10.4.16",
    "dotenv": "^16.3.1",
    "postcss": "^8.4.31",
    "tailwindcss": "^3.3.5",
    "vite": "^4.4.9"
  }
}

```

Env file exists:

![image](https://github.com/runtime-env/import-meta-env/assets/779656/7bd4cd64-3f84-46c3-bcd3-86d2f777aedf)

**Comment by Baldinof** [comment]
Hello, same error here. Did you find a workaround?

**Comment by soc221b** [comment]
To prevent accidentally leaking environment variables to the client, you need to list public environment variables in an example file (e.g., .env.example), and explicitly define it via the `example` plugin option:

```diff
import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'
import ImportMetaEnvPlugin from "@import-meta-env/unplugin"

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [    
    ImportMetaEnvPlugin.vite({
+     example: ".env.example",
      env: ".env"
    }),
    vue()
  ],
  envDir: './',
  server: {
    port: 3000,
    host: "0.0.0.0"
  },
  base: "/test/"
})
```

https://import-meta-env.org/guide/getting-started/compile-time-transform.html#plugin-options
